/**
 * Payment Engine — identifier generation (P0).
 *
 * §3.5: every attempt carries, generated by the ENGINE (never by a connector):
 *   GlobalPaymentId — uuid ADDX, created BEFORE any provider exchange;
 *   PaymentAttemptId — uuid, stable for the attempt's whole life;
 *   IdempotencyKey — DETERMINISTIC, derived from PaymentAttemptId (identical on
 *   every technical retry — fixes the non-deterministic key of
 *   useStripeTerminal.ts makeIdempotencyKey, écart §2.3.3).
 */

function uuid(): string {
  const c: Crypto | undefined = (globalThis as { crypto?: Crypto }).crypto;
  if (c?.randomUUID) return c.randomUUID();
  // Non-crypto fallback (old WebViews) — uniqueness only, not security.
  let out = '';
  const hex = '0123456789abcdef';
  for (let i = 0; i < 36; i++) {
    if (i === 8 || i === 13 || i === 18 || i === 23) out += '-';
    else if (i === 14) out += '4';
    else out += hex[Math.floor(Math.random() * 16)];
  }
  return out;
}

/** Deterministic payment idempotency key for an attempt — same on every retry. */
export function attemptIdempotencyKey(attemptId: string): string {
  return `pay_${attemptId}`;
}

/** Deterministic refund idempotency key — one referenced FULL refund per attempt (D-PE3). */
export function refundIdempotencyKey(attemptId: string): string {
  return `refund_${attemptId}`;
}

export interface PaymentIdentifiers {
  globalPaymentId: string;
  attemptId: string;
  idempotencyKey: string;
}

/**
 * Mint the identifiers of a NEW attempt. Call BEFORE any provider exchange.
 * A technical retry of the SAME attempt must reuse these — never re-mint.
 */
export function newPaymentIdentifiers(): PaymentIdentifiers {
  const globalPaymentId = uuid();
  const attemptId = uuid();
  return { globalPaymentId, attemptId, idempotencyKey: attemptIdempotencyKey(attemptId) };
}

/**
 * A follow-up attempt for the SAME sale (explicit retry after a resolved
 * failure) keeps the sale's GlobalPaymentId lineage separate: each attempt has
 * its own attemptId + key, under a NEW globalPaymentId is NOT minted — the
 * GlobalPaymentId identifies the payment intent of the sale leg, the attempt
 * identifies one presentation (§3.4).
 */
export function newAttemptForPayment(globalPaymentId: string): PaymentIdentifiers {
  const attemptId = uuid();
  return { globalPaymentId, attemptId, idempotencyKey: attemptIdempotencyKey(attemptId) };
}
