/**
 * Payment Engine — provider contract & core value types (P0).
 *
 * Reference: docs/payment-engine.md §3.2 (interface unique), §3.4 (concepts),
 * §3.5 (idempotence & GlobalPaymentId), §3.10 (PCI — interdictions absolues).
 *
 * Conformity rules (checklist §7):
 *  - 100 % generic: NOTHING Stripe/CIC/Adyen-specific may appear here.
 *  - The engine generates every identifier; a provider NEVER generates keys.
 *  - Provider references are only ever attached UNDER a GlobalPaymentId.
 *  - `raw` metadata is allowlist-filtered before persistence — never PAN/track/
 *    CVV/PIN/EMV data (§3.10).
 */

import type { PaymentAttemptStatus } from './states';

/** What the hardware/provider can do — the engine adapts flow & UX to this. */
export interface ProviderCapabilities {
  /** Referenced refund of a captured transaction (D-PE3: full refunds only). */
  refund: boolean;
  /** Cancellation before/during card presentation. */
  cancel: boolean;
  /** Post-transaction status query — required for VERIFICATION_REQUIRED resolution. */
  statusQuery: boolean;
  /** Separate authorization / capture phases. */
  separateAuthCapture: boolean;
}

/** Network is a connector detail — the engine makes NO assumption (§3.2). */
export interface TerminalConnection {
  type: 'internet' | 'ethernet' | 'wifi' | 'usb' | 'serial' | 'bluetooth' | 'cloud';
  /** IP / hostname for network links (e.g. a fixed RJ45 TPE address). */
  address?: string;
  port?: number;
}

/** Per-terminal configuration — NEVER contains secrets (referenced by name only). */
export interface TerminalConfig {
  provider: string;
  /** Our DB terminal id (payment_terminals) when enrolled. */
  terminalId?: string;
  label?: string;
  connection?: TerminalConnection;
  /** Non-sensitive provider config: merchant-id, location-id, … */
  providerConfig?: Record<string, string | number | boolean>;
  timeoutMs?: number;
}

export interface ProviderHealth {
  ok: boolean;
  detail?: string;
}

/**
 * ONE presentation of a payment to the customer (§3.4). All identifiers are
 * generated by the ENGINE before any provider exchange (§3.5) — see
 * identifiers.ts. A provider receives them, never creates them.
 */
export interface PaymentAttempt {
  /** ADDX-wide reference id — every provider ref attaches UNDER it, never the reverse. */
  globalPaymentId: string;
  /** Stable for the whole life of this attempt. */
  attemptId: string;
  /** Deterministic (derived from attemptId): identical on every technical retry. */
  idempotencyKey: string;
  amountMinorUnits: number;
  currency: string;
  saleId?: string;
  storeId?: string;
  terminalId?: string;
  cashSessionId?: string;
}

/** Canonical outcome of a provider operation — connectors map THEIR states to this. */
export type ProviderOutcome =
  | 'approved'
  | 'declined'
  | 'cancelled'
  | 'timeout'
  | 'communication_error'
  | 'unknown';

/**
 * Normalized result (§3.2). PCI §3.10: maskedPan is the ONLY card-number form
 * allowed anywhere; `raw` must already be allowlist-filtered by the connector.
 */
export interface ProviderResult {
  outcome: ProviderOutcome;
  /** Provider transaction reference (PaymentIntent id, CIC tx ref, …). */
  providerRef?: string;
  authorizationCode?: string;
  acquirerRRN?: string;
  /** e.g. '**** 1234' — never a full PAN. */
  maskedPan?: string;
  /** Card scheme: CB, VISA, MC, … */
  scheme?: string;
  errorCode?: string;
  errorMessage?: string;
  /** Non-sensitive, allowlist-filtered metadata only. */
  raw?: Record<string, string | number | boolean>;
}

/** Post-transaction status as reported by the provider (reconciliation, §3.8). */
export type ProviderTxState =
  | 'approved'
  | 'declined'
  | 'cancelled'
  | 'pending'
  | 'not_found'
  | 'unknown';

export interface ProviderTxStatus {
  state: ProviderTxState;
  providerRef?: string;
  amountMinorUnits?: number;
  currency?: string;
  authorizationCode?: string;
  acquirerRRN?: string;
}

/** Referenced FULL refund request (D-PE3) — never a blind negative payment. */
export interface RefundRequest {
  globalPaymentId: string;
  /** Deterministic refund idempotency key, generated by the engine. */
  idempotencyKey: string;
  /** Reference of the captured transaction being refunded. */
  providerRef: string;
  amountMinorUnits: number;
  currency: string;
  saleId?: string;
  storeId?: string;
}

/**
 * Contrat unique — chaque connecteur l'implémente intégralement (§3.2).
 * 'stripe' | 'cic' | 'worldline' | 'manual' | 'mock' | … — no closed list.
 */
export interface PaymentProvider {
  readonly name: string;

  capabilities(): ProviderCapabilities;

  /** Lifecycle — config never carries raw secrets. */
  init(config: TerminalConfig): Promise<void>;
  connect(): Promise<void>;
  disconnect(): Promise<void>;
  healthcheck(): Promise<ProviderHealth>;
  reconnect(): Promise<void>;

  /** Payment. `attempt` carries ALL keys — the provider generates none. */
  collect(attempt: PaymentAttempt): Promise<ProviderResult>;
  /** Cancellation before/during card presentation. */
  cancel(attemptId: string): Promise<ProviderResult>;

  /** Post-transaction. */
  getStatus(providerRef: string): Promise<ProviderTxStatus>;
  refund(req: RefundRequest): Promise<ProviderResult>;
}

/** Journal entry shape (§3.9) — append-only, same discipline as audit_entry. */
export interface PaymentJournalEntry {
  globalPaymentId: string;
  attemptId: string;
  saleId?: string;
  storeId?: string;
  terminalId?: string;
  cashSessionId?: string;
  provider: string;
  amountMinorUnits: number;
  currency: string;
  from: PaymentAttemptStatus | null;
  to: PaymentAttemptStatus;
  at: string;
  /** 'cashier' | 'system' | 'manager' — who caused the transition. */
  actor: string;
  providerRef?: string;
  authorizationCode?: string;
  acquirerRRN?: string;
  errorCode?: string;
  durationMs?: number;
}
